### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by ericbf** [jbrower95/Explicitor#2]
It runs now, thanks to the inclusion of the library, but I'm getting this error after the second to last song is completed (according to the terminal output)

Exception in thread "Thread-4" java.lang.NullPointerException
    at com.sun.media.sound.WaveFileReader.getAudioInputStream(WaveFileReader.java:180)
    at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1128)
    at EmptyFrame1.success(Frame.java:780)
    at EmptyFrame1.got(Frame.java:704)
    at DownloadManager.run(Frame.java:1479)
    at java.lang.Thread.run(Thread.java:680)

**Comment by jbrower95** [comment]
Fantastic. it's essentially a problem with the inclusion of the small 'success' sound that plays when the application finishes loading. I can fix this easily. I'm just glad that was the only error you got.

**Comment by ericbf** [comment]
It’s been ten years now. Just closing this.
